BookLog/Controllers/BooksController.cs
using BookLog.Dtos;
using BookLog.Services;
using BookLog.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace BookLog.Controllers {
    public class BooksController : Controller {
        private BookService _bookService;
        private AuthorService _authorService;
        private GenreService _genreService;
        private ReviewService _reviewService;

        public BooksController(
            BookService bookService, AuthorService authorService, GenreService genreService, ReviewService reviewService) {
            _bookService = bookService;
            _authorService = authorService;
            _genreService = genreService;
            _reviewService = reviewService;
        }

        public async Task<IActionResult> Index() {
            var allBooks = await _bookService.GetAllAsync();
            return View(allBooks);
        }

        public async Task<IActionResult> Create() {
            var newBook = new BookCreateEditDto() {
                Authors = (await _authorService.GetAllAsync()).ToList(),
                Genres = (await _genreService.GetAllAsync()).ToList(),
            };
            return View(newBook);
        }

        [HttpPost]
        public async Task<IActionResult> Create(BookCreateEditDto newBook) {
            if (!ModelState.IsValid) {
                newBook.Authors = (await _authorService.GetAllAsync()).ToList();
                newBook.Genres = (await _genreService.GetAllAsync()).ToList();
                return View(newBook);
            }
            await _bookService.CreateAsync(newBook);
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Edit(int id) {
            var bookToEdit = await _bookService.GetByIdAsync(id);
            return bookToEdit != null ? View(bookToEdit) : View("NotFound");
        }

        [HttpPost]
        public async Task<IActionResult> Edit(BookCreateEditDto bookCreateEditDto) {
            if (!ModelState.IsValid) {
                bookCreateEditDto.Authors = (await _authorService.GetAllAsync()).ToList();
                bookCreateEditDto.Genres = (await _genreService.GetAllAsync()).ToList();
                return View(bookCreateEditDto);
            }
            await _bookService.UpdateAsync(bookCreateEditDto);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id) {
            var deleted = await _bookService.DeleteAsync(id);
            if (!deleted) {
                return View("NotFound");
            }
            return RedirectToAction("Index");
        }

        public IActionResult Search(string query) {
            var foundBooks = _bookService.GetByTextInTitle(query);
            return View("Index", foundBooks);
        }

        public IActionResult CancelFilter() {
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Details(int id) {
            var book = await _reviewService.GetBookDetailsAsync(id);
            if (book == null) {
                return View("NotFound");
            }
            var reviews = await _reviewService.GetByBookIdAsync(id);
            var bookDetailsVM = new BookDetailsViewModel() {
                Book = book,
                Reviews = reviews,
                NewReview = new ReviewCreateDto() {
                    BookId = id,
                },
            };
            return View(bookDetailsVM);
        }
    }
}

BookLog/Controllers/GenresController.cs
using BookLog.Dtos;
using BookLog.Services;
using Microsoft.AspNetCore.Mvc;

namespace BookLog.Controllers {
    public class GenresController : Controller {
        private GenreService _service;

        public GenresController(GenreService service) {
            _service = service;
        }

        public async Task<IActionResult> IndexAsync() {
            var allGenres = await _service.GetAllAsync();
            return View(allGenres);
        }

        public IActionResult Create() {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(GenreDto newGenre) {
            await _service.CreateAsync(newGenre);
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Edit(int id) {
            var genreToEdit = await _service.GetByIdAsync(id);
            return genreToEdit != null ? View(genreToEdit) : View("NotFound");
        }

        [HttpPost]
        public async Task<IActionResult> Edit(GenreDto genreDto) {
            await _service.UpdateAsync(genreDto);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id) {
            var deleted = await _service.DeleteAsync(id);
            if (!deleted) {
                return View("NotFound");
            }
            return RedirectToAction("Index");
        }
    }
}

BookLog/Controllers/ReviewsController.cs
using BookLog.Dtos;
using BookLog.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace BookLog.Controllers {
    public class ReviewsController : Controller {
        private ReviewService _service;

        public ReviewsController(ReviewService service) {
            _service = service;
        }

        public IActionResult Index() {
            return View();
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Create(ReviewCreateDto reviewCreateDto) {
            if (!ModelState.IsValid) {
                return RedirectToAction("Details", "Books", new { id = reviewCreateDto.BookId });
            }
            var userName = User.Identity!.Name!;
            await _service.CreateAsync(reviewCreateDto, userName);
            return RedirectToAction("Details", "Books", new { id = reviewCreateDto.BookId });
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int reviewId, int bookId) {
            var deleted = await _service.DeleteAsync(reviewId);
            if (!deleted) {
                return View("NotFound");
            };
            return RedirectToAction("Details", "Books", new { id = bookId });
        }
    }
}

BookLog/Controllers/RolesController.cs
using BookLog.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace BookLog.Controllers {
    [Authorize(Roles = "Administrator")]
    public class RolesController : Controller {
        private RoleManager<IdentityRole> _roleManager;
        private UserManager<AppUser> _userManager; 

        public RolesController(RoleManager<IdentityRole> roleManager, UserManager<AppUser> userManager) {
            _roleManager = roleManager;
            _userManager = userManager;
        }

        public IActionResult Index() {
            return View(_roleManager.Roles);
        }

        public IActionResult Create() => View();

        [HttpPost]
        public async Task<IActionResult> CreateAsync(string name) {
            if (ModelState.IsValid) {
                IdentityResult result = await _roleManager.CreateAsync(new IdentityRole(name));
                if (result.Succeeded) {
                    return RedirectToAction("Index");
                }
                AddErrors(result);
            }
            return View("Create", name);
        }

        public async Task<IActionResult> EditAsync(string id) {
            var role = await _roleManager.FindByIdAsync(id);
            if (role == null) {
                return View("NotFound");
            }
            var members = new List<AppUser>();
            var nonMembers = new List<AppUser>();
            foreach (AppUser user in _userManager.Users) {
                var list = await _userManager.IsInRoleAsync(user, role.Name!) ? members : nonMembers;
                list.Add(user);
            }
            return View(new RoleEdit {
                Role = role,
                Members = members,
                NonMembers = nonMembers,
            });
        }

        [HttpPost]
        public async Task<IActionResult> EditAsync(RoleModification model) {
            IdentityResult result;
            if (ModelState.IsValid) {
                foreach (string userId in model.IdsToAdd ?? []) {
                    var user = await _userManager.FindByIdAsync(userId);
                    if (user != null) {
                        result = await _userManager.AddToRoleAsync(user, model.RoleName);
                        if (!result.Succeeded) {
                            AddErrors(result);
                        }
                    }
                }
                foreach (string userId in model.IdsToDelete ?? []) {
                    var user = await _userManager.FindByIdAsync(userId);
                    if (user != null) {
                        result = await _userManager.RemoveFromRoleAsync(user, model.RoleName);
                        if (!result.Succeeded) {
                            AddErrors(result);
                        }
                    }
                }
                if (ModelState.IsValid) {
                    return RedirectToAction("Index");
                }
            }
            return await EditAsync(model.RoleId);
        }

        [HttpPost]
        public async Task<IActionResult> DeleteAsync(string id) {
            var role = await _roleManager.FindByIdAsync(id);
            if (role != null) {
                IdentityResult result = await _roleManager.DeleteAsync(role);
                if (result.Succeeded) {
                    return RedirectToAction("Index");
                }
                AddErrors(result);
            }
            else {
                ModelState.AddModelError("", "Role not found.");
            }
            return View("Index", _roleManager.Roles);
        }

        private void AddErrors(IdentityResult result) {
            foreach (IdentityError error in result.Errors) {
                ModelState.AddModelError("", error.Description);
            }
        }
    }
}

BookLog/Controllers/UsersController.cs
using BookLog.Models;
using BookLog.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace BookLog.Controllers {
    [Authorize(Roles = "Administrator")]
    public class UsersController : Controller {
        private UserManager<AppUser> _userManager;
        private IPasswordHasher<AppUser> _passwordHasher;
        private IPasswordValidator<AppUser> _passwordValidator;

        public UsersController(
            UserManager<AppUser> userManager,
            IPasswordHasher<AppUser> passwordHasher,
            IPasswordValidator<AppUser> passwordValidator) {
            _userManager = userManager;
            _passwordHasher = passwordHasher;
            _passwordValidator = passwordValidator;
        }

        public IActionResult Index() {
            return View(_userManager.Users);
        }

        public IActionResult Create() => View();

        [HttpPost]
        public async Task<IActionResult> Create(UserViewModel user) {
            if (ModelState.IsValid) {
                var appUser = new AppUser {
                    UserName = user.Name,
                    Email = user.Email,
                };
                IdentityResult result = await _userManager.CreateAsync(appUser, user.Password);
                if (result.Succeeded) {
                    return RedirectToAction("Index");
                }
                AddErrors(result);
            }
            return View(user);
        }

        public async Task<IActionResult> Edit(string id) {
            var userToEdit = await _userManager.FindByIdAsync(id);
            if (userToEdit == null) {
                return View("NotFound");
            }
            var userToEditVM = new EditUserViewModel {
                Id = userToEdit.Id,
                Name = userToEdit.UserName!,
                Email = userToEdit.Email!,
            };
            return View(userToEditVM);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(EditUserViewModel user) {
            if (!ModelState.IsValid) {
                return View(user);
            }
            var appUser = await _userManager.FindByIdAsync(user.Id);
            if (appUser == null) {
                ModelState.AddModelError("", "User not found.");
                return View(user);
            }
            IdentityResult passwordValidation = await _passwordValidator.ValidateAsync(
                _userManager, appUser, user.Password);
            if (!passwordValidation.Succeeded) {
                AddErrors(passwordValidation);
                return View(user);
            }
            appUser.Email = user.Email;
            appUser.PasswordHash = _passwordHasher.HashPassword(appUser, user.Password);
            IdentityResult result = await _userManager.UpdateAsync(appUser);
            if (result.Succeeded) {
                return RedirectToAction("Index");
            }
            AddErrors(result);
            return View(user);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(string id) {
            var user = await _userManager.FindByIdAsync(id);
            if (user != null) {
                IdentityResult result = await _userManager.DeleteAsync(user);
                if (result.Succeeded) {
                    return RedirectToAction("Index");
                }
                AddErrors(result);
            }
            else {
                ModelState.AddModelError("", "User not found.");
            }
            return View("Index", _userManager.Users);
        }

        private void AddErrors(IdentityResult result) {
            foreach (IdentityError error in result.Errors) {
                ModelState.AddModelError("", error.Description);
            }
        }
    }
}

BookLog/Views/Shared/AccessDenied.cshtml
<h2 class="bg-danger mb-1 p-2 text-white">Access Denied</h2>

BookLog/Views/Shared/NotFound.cshtml
<h1>Not Found!</h1>

BookLog/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BookLog</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BookLog.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BookLog</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Home" asp-action="About">About</a>
                        </li>
                        @if (User?.Identity?.IsAuthenticated == true && (User.IsInRole("User") || User.IsInRole("Administrator"))) {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Books" asp-action="Index">Books</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Authors" asp-action="Index">Authors</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Genres" asp-action="Index">Genres</a>
                            </li>
                        }
                        @if (User?.Identity?.IsAuthenticated == true && User.IsInRole("Administrator")) {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Users" asp-action="Index">Users</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Roles" asp-action="Index">Roles</a>
                            </li>
                        }
                    </ul>
                </div>
                @if (User?.Identity?.IsAuthenticated ?? false) {
                    <a asp-controller="Account" asp-action="Logout" class="btn btn-danger me-3">Logout</a>
                }

            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 Dušan Kovářík - BookLog - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

BookLog/Views/Shared/_ReviewForm.cshtml
@using BookLog.Dtos

@model ReviewCreateDto

<input type="hidden" asp-for="BookId" />

<div class="mb-2">
    <label asp-for="Rating"></label>
    <select asp-for="Rating" class="form-select">
        <option value="">Select rating</option>
        <option value="1">⭐ 1</option>
        <option value="2">⭐⭐ 2</option>
        <option value="3">⭐⭐⭐ 3</option>
        <option value="4">⭐⭐⭐⭐ 4</option>
        <option value="5">⭐⭐⭐⭐⭐ 5</option>
    </select>
    <span asp-validation-for="Rating" class="text-danger"></span>
</div>

<div class="mb-2">
    <label asp-for="Text"></label>
    <textarea asp-for="Text" class="form-control"></textarea>
    <span asp-validation-for="Text" class="text-danger"></span>
</div>